UPDATE COMPANY_INFO SET INTEGRAL=0;
-------------------------------------SL_DATA---------------------------------------
--建表
DECLARE t_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO t_num FROM user_tables WHERE table_name='SL_DATA';
  IF t_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP TABLE "SL_DATA"';
  END IF;
END;
/
CREATE TABLE "SL_DATA" 
(	
	"ID" NUMBER(12,0) NOT NULL PRIMARY KEY,
	"REAL_NAME" VARCHAR2(60 BYTE) NULL,
	"ID_CARD" VARCHAR2(18 BYTE) NULL,
	"COMPANY_ID" NUMBER(12,0) NOT NULL,
	"COMPANY_CODE" VARCHAR2(17 BYTE) NULL,
	"BORROW_TYPE" NUMBER(2,0) NULL,
	"BORROW_STATE" NUMBER(2,0) NULL,
	"BORROW_AMOUNT" NUMBER(2,0) DEFAULT '0' NULL,
	"CONTRACT_DATE" NUMBER(16,0) NOT NULL,
	"LOAN_PERIOD" NUMBER(2,0) DEFAULT '0' NULL,
	"REPAY_STATE" NUMBER(2,0) NULL,
	"ARREARS_AMOUNT" NUMBER(19,0) NOT NULL,
	"REC_TIME" NUMBER(16,0) NOT NULL
);
--设置字段备注
COMMENT ON COLUMN "SL_DATA"."ID" IS '标识列';
COMMENT ON COLUMN "SL_DATA"."REAL_NAME" IS '姓名';
COMMENT ON COLUMN "SL_DATA"."ID_CARD" IS '身份证号';
COMMENT ON COLUMN "SL_DATA"."COMPANY_ID" IS '请求公司ID';
COMMENT ON COLUMN "SL_DATA"."COMPANY_CODE" IS '公司编码';
COMMENT ON COLUMN "SL_DATA"."BORROW_TYPE" IS '借款类型 0.未知1.个人信贷2.个人抵押3.企业信贷4.企业抵押';
COMMENT ON COLUMN "SL_DATA"."BORROW_STATE" IS '借款状态 0.未知1.拒贷2.批贷已放款3.批贷未放款4.借款人放弃申请5.审核中6.待放款';
COMMENT ON COLUMN "SL_DATA"."BORROW_AMOUNT" IS '借款金额 0.未知 1.[0,2], 2.[2,4], 3.[4,6], 4.[6,8] ........';
COMMENT ON COLUMN "SL_DATA"."CONTRACT_DATE" IS '合同日期';
COMMENT ON COLUMN "SL_DATA"."LOAN_PERIOD" IS '批贷期数';
COMMENT ON COLUMN "SL_DATA"."REPAY_STATE" IS '还款状态 0.未知1.正常2.M1 3.M2 4.M3 5.M4 6.M5 7.M6 8.M6+ 9.已还清';
COMMENT ON COLUMN "SL_DATA"."ARREARS_AMOUNT" IS '欠款金额';
COMMENT ON COLUMN "SL_DATA"."REC_TIME" IS '创建时间';
--创建序列
DECLARE s_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO s_num FROM user_sequences WHERE sequence_name= 'SL_DATA_ID_SEQUENCE';
  IF s_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SL_DATA_ID_SEQUENCE';
  END IF;
END;
/
CREATE SEQUENCE SL_DATA_ID_SEQUENCE
INCREMENT BY 1  --每次增加几个
MINVALUE 1      --最小值为1
NOMAXVALUE      --不限制最大值
START WITH 1    --从1开始
CACHE 10        --缓存
ORDER;
--------------------------------------------------------------------------------------------
-------------------------------------SEARCH_LOG---------------------------------------
--建表
DECLARE t_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO t_num FROM user_tables WHERE table_name='SEARCH_LOG';
  IF t_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP TABLE "SEARCH_LOG"';
  END IF;
END;
/
CREATE TABLE "SEARCH_LOG" 
(	
	"ID" NUMBER(12,0) NOT NULL PRIMARY KEY,
	"SEARCH_TRX_NO" VARCHAR2(32 BYTE) NULL,
	"REAL_NAME" VARCHAR2(60 BYTE) NULL,
	"ID_CARD" VARCHAR2(18 BYTE) NULL,
	"REQ_COMPANY_ID" NUMBER(12,0) NOT NULL,
	"REQ_COMPANY_CODE" VARCHAR2(17 BYTE) NULL,
	"STATE" NUMBER(2,0) NULL,
	"SYNC_STATE" NUMBER(2,0) NULL,
	"SEARCH_TYPE" NUMBER(2,0) NULL,
	"REC_TIME" NUMBER(16,0) NOT NULL,
	"END_TIME" NUMBER(16,0) NOT NULL
);
--设置字段备注
COMMENT ON COLUMN "SEARCH_LOG"."ID" IS '标识列';
COMMENT ON COLUMN "SEARCH_LOG"."SEARCH_TRX_NO" IS '查询流水号';
COMMENT ON COLUMN "SEARCH_LOG"."REAL_NAME" IS '姓名';
COMMENT ON COLUMN "SEARCH_LOG"."ID_CARD" IS '身份证号';
COMMENT ON COLUMN "SEARCH_LOG"."REQ_COMPANY_ID" IS '请求公司ID';
COMMENT ON COLUMN "SEARCH_LOG"."REQ_COMPANY_CODE" IS '公司编码';
COMMENT ON COLUMN "SEARCH_LOG"."STATE" IS '异步状态 0.未知1.待查询 2.查询中 3.待反馈结果 4.反馈次数上限 5.回调上报已完成6.非回调上报完成';
COMMENT ON COLUMN "SEARCH_LOG"."SYNC_STATE" IS '同步状态 0.未知1.查询中 2.已完成3.需重复报送';
COMMENT ON COLUMN "SEARCH_LOG"."SEARCH_TYPE" IS '查询类型 0.旧异步接口查询1.网站查询2.网站批量查询3.快速查询接口4.新异步接口查询';
COMMENT ON COLUMN "SEARCH_LOG"."REC_TIME" IS '创建时间';
COMMENT ON COLUMN "SEARCH_LOG"."END_TIME" IS '完成时间';
--创建序列
DECLARE s_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO s_num FROM user_sequences WHERE sequence_name= 'SEARCH_LOG_ID_SEQUENCE';
  IF s_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEARCH_LOG_ID_SEQUENCE';
  END IF;
END;
/
CREATE SEQUENCE SEARCH_LOG_ID_SEQUENCE
INCREMENT BY 1  --每次增加几个
MINVALUE 1      --最小值为1
NOMAXVALUE      --不限制最大值
START WITH 1    --从1开始
CACHE 10        --缓存
ORDER;
--------------------------------------------------------------------------------------------
-------------------------------------SEARCH_RESULT---------------------------------------
--建表
DECLARE t_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO t_num FROM user_tables WHERE table_name='SEARCH_RESULT';
  IF t_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP TABLE "SEARCH_RESULT"';
  END IF;
END;
/
CREATE TABLE "SEARCH_RESULT" 
(	
	"ID" NUMBER(12,0) NOT NULL PRIMARY KEY,
	"SEARCH_LOG_ID" NUMBER(12,0) NOT NULL,
	"SEARCH_TRX_NO" VARCHAR2(32 BYTE) NULL,
	"RSP_COMPANY_ID" NUMBER(12,0) NOT NULL,
	"RSP_COMPANY_CODE" VARCHAR2(17 BYTE) NULL,
	"BORROW_TYPE" NUMBER(2,0) NULL,
	"BORROW_STATE" NUMBER(2,0) NULL,
	"BORROW_AMOUNT" NUMBER(2,0) DEFAULT '0' NULL,
	"CONTRACT_DATE" NUMBER(16,0) NOT NULL,
	"LOAN_PERIOD" NUMBER(2,0) DEFAULT '0' NULL,
	"REPAY_STATE" NUMBER(2,0) NULL,
	"ARREARS_AMOUNT" NUMBER(19,0) NOT NULL,
	"REC_TIME" NUMBER(16,0) NOT NULL,
	"RESULT_TYPE" NUMBER(2,0) DEFAULT '0' NULL,
	"DATA_TYPE" NUMBER(2,0) DEFAULT '0' NULL
);
--设置字段备注
COMMENT ON COLUMN "SEARCH_RESULT"."ID" IS '标识列';
COMMENT ON COLUMN "SEARCH_RESULT"."SEARCH_LOG_ID" IS '查询ID';
COMMENT ON COLUMN "SEARCH_RESULT"."SEARCH_TRX_NO" IS '查询流水号';
COMMENT ON COLUMN "SEARCH_RESULT"."RSP_COMPANY_ID" IS '请求公司ID';
COMMENT ON COLUMN "SEARCH_RESULT"."RSP_COMPANY_CODE" IS '公司编码';
COMMENT ON COLUMN "SEARCH_RESULT"."BORROW_TYPE" IS '借款类型 0.未知1.个人信贷2.个人抵押3.企业信贷4.企业抵押';
COMMENT ON COLUMN "SEARCH_RESULT"."BORROW_STATE" IS '借款状态 0.未知1.拒贷2.批贷已放款3.批贷未放款4.借款人放弃申请5.审核中6.待放款';
COMMENT ON COLUMN "SEARCH_RESULT"."BORROW_AMOUNT" IS '借款金额 0.未知 1.[0,2], 2.[2,4], 3.[4,6], 4.[6,8] ........';
COMMENT ON COLUMN "SEARCH_RESULT"."CONTRACT_DATE" IS '合同日期';
COMMENT ON COLUMN "SEARCH_RESULT"."LOAN_PERIOD" IS '批贷期数';
COMMENT ON COLUMN "SEARCH_RESULT"."REPAY_STATE" IS '还款状态 0.未知1.正常2.M1 3.M2 4.M3 5.M4 6.M5 7.M6 8.M6+ 9.已还清';
COMMENT ON COLUMN "SEARCH_RESULT"."ARREARS_AMOUNT" IS '欠款金额';
COMMENT ON COLUMN "SEARCH_RESULT"."REC_TIME" IS '创建时间';
COMMENT ON COLUMN "SEARCH_RESULT"."RESULT_TYPE" IS '记录类型 0.常规记录1.快速查询记录同步2.快速查询记录异步';
COMMENT ON COLUMN "SEARCH_RESULT"."DATA_TYPE" IS '记录类型 0.常规记录1.JD_DATA2.SL_DATA';
--创建序列
DECLARE s_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO s_num FROM user_sequences WHERE sequence_name= 'SEARCH_RESULT_ID_SEQUENCE';
  IF s_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEARCH_RESULT_ID_SEQUENCE';
  END IF;
END;
/
CREATE SEQUENCE SEARCH_RESULT_ID_SEQUENCE
INCREMENT BY 1  --每次增加几个
MINVALUE 1      --最小值为1
NOMAXVALUE      --不限制最大值
START WITH 1    --从1开始
CACHE 10        --缓存
ORDER;
--------------------------------------------------------------------------------------------
-------------------------------------INTEGRAL_LOG---------------------------------------
--建表
DECLARE t_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO t_num FROM user_tables WHERE table_name='INTEGRAL_LOG';
  IF t_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP TABLE "INTEGRAL_LOG"';
  END IF;
END;
/
CREATE TABLE "INTEGRAL_LOG" 
(	
	"ID" NUMBER(12,0) NOT NULL PRIMARY KEY,
	"REQ_COMPANY_ID" NUMBER(12,0) NOT NULL,
	"REQ_COMPANY_CODE" VARCHAR2(17 BYTE) NULL,
	"RSP_COMPANY_ID" NUMBER(12,0) NOT NULL,
	"RSP_COMPANY_CODE" VARCHAR2(17 BYTE) NULL,
	"SEARCH_LOG_ID" NUMBER(12,0) NOT NULL,
	"SEARCH_TRX_NO" VARCHAR2(32 BYTE) NULL,
	"BORROW_TYPE" NUMBER(2,0) NULL,
	"BORROW_STATE" NUMBER(2,0) NULL,
	"BORROW_AMOUNT" NUMBER(2,0) NULL,
	"CONTRACT_DATE" NUMBER(2,0) NULL,
	"LOAN_PERIOD" NUMBER(2,0) DEFAULT '0' NULL,
	"REPAY_STATE" NUMBER(2,0) NULL,
	"ARREARS_AMOUNT" NUMBER(2,0) NULL,
	"INTEGRAL_SUM" NUMBER(19,0) NOT NULL,
	"REC_TIME" NUMBER(16,0) NOT NULL
);
--设置字段备注
COMMENT ON COLUMN "INTEGRAL_LOG"."ID" IS '标识列';
COMMENT ON COLUMN "INTEGRAL_LOG"."REQ_COMPANY_ID" IS '请求公司ID';
COMMENT ON COLUMN "INTEGRAL_LOG"."REQ_COMPANY_CODE" IS '请求公司编码';
COMMENT ON COLUMN "INTEGRAL_LOG"."RSP_COMPANY_ID" IS '响应公司ID';
COMMENT ON COLUMN "INTEGRAL_LOG"."RSP_COMPANY_CODE" IS '响应公司编码';
COMMENT ON COLUMN "INTEGRAL_LOG"."SEARCH_LOG_ID" IS '查询ID';
COMMENT ON COLUMN "INTEGRAL_LOG"."SEARCH_TRX_NO" IS '查询流水号';
COMMENT ON COLUMN "INTEGRAL_LOG"."BORROW_TYPE" IS '借款类型 0.无1.有';
COMMENT ON COLUMN "INTEGRAL_LOG"."BORROW_STATE" IS '借款状态 0.无1.有';
COMMENT ON COLUMN "INTEGRAL_LOG"."BORROW_AMOUNT" IS '借款金额 0.无1.有';
COMMENT ON COLUMN "INTEGRAL_LOG"."CONTRACT_DATE" IS '合同日期  0.无1.有';
COMMENT ON COLUMN "INTEGRAL_LOG"."LOAN_PERIOD" IS '批贷期数  0.无1.有';
COMMENT ON COLUMN "INTEGRAL_LOG"."REPAY_STATE" IS '还款状态  0.无1.有';
COMMENT ON COLUMN "INTEGRAL_LOG"."ARREARS_AMOUNT" IS '欠款金额  0.无1.有';
COMMENT ON COLUMN "INTEGRAL_LOG"."INTEGRAL_SUM" IS '积分';
COMMENT ON COLUMN "INTEGRAL_LOG"."REC_TIME" IS '创建时间';
--创建序列
DECLARE s_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO s_num FROM user_sequences WHERE sequence_name= 'INTEGRAL_LOG_ID_SEQUENCE';
  IF s_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE INTEGRAL_LOG_ID_SEQUENCE';
  END IF;
END;
/
CREATE SEQUENCE INTEGRAL_LOG_ID_SEQUENCE
INCREMENT BY 1  --每次增加几个
MINVALUE 1      --最小值为1
NOMAXVALUE      --不限制最大值
START WITH 1    --从1开始
CACHE 10        --缓存
ORDER;
--------------------------------------------------------------------------------------------
-------------------------------------SEARCH_COUNT---------------------------------------
--建表
DECLARE t_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO t_num FROM user_tables WHERE table_name='SEARCH_COUNT';
  IF t_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP TABLE "SEARCH_COUNT"';
  END IF;
END;
/
CREATE TABLE "SEARCH_COUNT" 
(	
	"ID" NUMBER(12,0) NOT NULL PRIMARY KEY,
	"COMPANY_ID" NUMBER(12,0) NOT NULL,
	"COMPANY_CODE" VARCHAR2(17 BYTE) NULL,
	"SEARCH_COUNT" NUMBER(6,0) NULL,
	"REC_TIME" NUMBER(16,0) NOT NULL
);
--设置字段备注
COMMENT ON COLUMN "SEARCH_COUNT"."ID" IS '标识列';
COMMENT ON COLUMN "SEARCH_COUNT"."COMPANY_ID" IS '公司ID';
COMMENT ON COLUMN "SEARCH_COUNT"."COMPANY_CODE" IS '公司编码';
COMMENT ON COLUMN "SEARCH_COUNT"."SEARCH_COUNT" IS '查询总数';
COMMENT ON COLUMN "SEARCH_COUNT"."REC_TIME" IS '创建时间';
--创建序列
DECLARE s_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO s_num FROM user_sequences WHERE sequence_name= 'SEARCH_COUNT_ID_SEQUENCE';
  IF s_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEARCH_COUNT_ID_SEQUENCE';
  END IF;
END;
/
CREATE SEQUENCE SEARCH_COUNT_ID_SEQUENCE
INCREMENT BY 1  --每次增加几个
MINVALUE 1      --最小值为1
NOMAXVALUE      --不限制最大值
START WITH 1    --从1开始
CACHE 10        --缓存
ORDER;
--------------------------------------------------------------------------------------------
-------------------------------------RESULT_NF_COUNT---------------------------------------
--建表
DECLARE t_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO t_num FROM user_tables WHERE table_name='RESULT_NF_COUNT';
  IF t_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP TABLE "RESULT_NF_COUNT"';
  END IF;
END;
/
CREATE TABLE "RESULT_NF_COUNT" 
(	
	"ID" NUMBER(12,0) NOT NULL PRIMARY KEY,
	"SEARCH_LOG_ID" NUMBER(12,0) NOT NULL,
	"SEARCH_TRX_NO" VARCHAR2(32 BYTE) NULL,
	"FAILED_COUNT" NUMBER(6,0) NULL,
	"REC_TIME" NUMBER(16,0) NOT NULL
);
--设置字段备注
COMMENT ON COLUMN "RESULT_NF_COUNT"."ID" IS '标识列';
COMMENT ON COLUMN "RESULT_NF_COUNT"."SEARCH_LOG_ID" IS '查询ID';
COMMENT ON COLUMN "RESULT_NF_COUNT"."SEARCH_TRX_NO" IS '查询流水号';
COMMENT ON COLUMN "RESULT_NF_COUNT"."FAILED_COUNT" IS '失败总数';
COMMENT ON COLUMN "RESULT_NF_COUNT"."REC_TIME" IS '创建时间';
--创建序列
DECLARE s_num NUMBER;
BEGIN
  SELECT COUNT(1) INTO s_num FROM user_sequences WHERE sequence_name= 'RESULT_NF_COUNT_ID_SEQUENCE';
  IF s_num = 1 THEN
    EXECUTE IMMEDIATE 'DROP SEQUENCE RESULT_NF_COUNT_ID_SEQUENCE';
  END IF;
END;
/
CREATE SEQUENCE RESULT_NF_COUNT_ID_SEQUENCE
INCREMENT BY 1  --每次增加几个
MINVALUE 1      --最小值为1
NOMAXVALUE      --不限制最大值
START WITH 1    --从1开始
CACHE 10        --缓存
ORDER;